const GET_SONG_REQUEST = 'GET_SONG_REQUEST';
const GET_SONG_SUCCESS = 'GET_SONG_SUCCESS';
const GET_SONG_ERROR = 'GET_SONG_ERROR';
const SET_SONG_REQUEST = 'SET_SONG_REQUEST';
const SET_SONG_SUCCESS = 'SET_SONG_SUCCESS';
const SET_SONG_ERROR = 'SET_SONG_ERROR';

export {
  GET_SONG_REQUEST,
  GET_SONG_SUCCESS,
  GET_SONG_ERROR,
  SET_SONG_REQUEST,
  SET_SONG_SUCCESS,
  SET_SONG_ERROR,
};
